application_setup = ANWENDUNG EINRICHTEN
guided_setup = Geführte Installation Ihrer Windows-Anwendung.
platform_windows = WINDOWS
action_required = AKTION ERFORDERLICH
setup_needs_attention = Das Setup benötigt Ihre Aufmerksamkeit
continue_action = Weiter
ok = OK
cancel = Abbrechen
abort = Abbrechen
retry = Wiederholen
try_again = Erneut versuchen
ignore = Ignorieren
yes = Ja
no = Nein
files_in_use = Schließen Sie Anwendungen, die installierte Dateien verwenden, und versuchen Sie es erneut.
welcome = WILLKOMMEN
preparing_setup = Setup wird vorbereitet
checking_installed_version = Installierte Version wird geprüft...
version_check = VERSIONSPRÜFUNG
newer_version_installed = Eine neuere Version ist installiert
remove_newer_version = Deinstallieren Sie die neuere Version, bevor Sie diese Version installieren.
close = Schließen
maintenance = WARTUNG
manage_installation = Installation verwalten
already_installed = Live2D Preview ist bereits installiert. Sie können die Anwendung reparieren oder von diesem Computer deinstallieren.
uninstall = Deinstallieren
repair = Reparieren
installation = INSTALLATION
ready_to_install = Bereit zur Installation
installation_options = Wählen Sie den Installationsort und ob eine Desktopverknüpfung erstellt werden soll.
installation_folder = Installationsordner
invalid_installation_folder = Geben Sie einen absoluten Pfad ein
browse = Durchsuchen...
create_desktop_shortcut = Desktopverknüpfung erstellen
install = Installieren
setup = SETUP
setup_could_not_continue = Setup kann nicht fortgesetzt werden
installed_version_unknown = Die installierte Version konnte nicht ermittelt werden.
installing = INSTALLATION
installing_product = Live2D Preview wird installiert
rollback = RÜCKGÄNGIG MACHEN
canceling_and_rolling_back = Vorgang wird abgebrochen und rückgängig gemacht
repairing = REPARATUR
repairing_product = Live2D Preview wird repariert
removing = DEINSTALLATION
uninstalling_product = Live2D Preview wird deinstalliert
operation_may_take_a_moment = Dieser Vorgang kann einen Moment dauern.
complete = ABGESCHLOSSEN
application_removed = Anwendung deinstalliert
installation_complete = Installation abgeschlossen
application_removed_message = Die Anwendung wurde von diesem Computer deinstalliert.
installation_complete_message = Live2D Preview wurde erfolgreich installiert.
application_removed_restart_message = Die Anwendung wurde von diesem Computer deinstalliert. Starten Sie Windows neu, um den Vorgang abzuschließen.
installation_complete_restart_message = Live2D Preview wurde erfolgreich installiert. Starten Sie Windows neu, um den Vorgang abzuschließen.
canceled = ABGEBROCHEN
installation_canceled = Installation abgebrochen
no_further_changes = Es werden keine weiteren Änderungen vorgenommen.
setup_error = SETUPFEHLER
installation_failed = Installation fehlgeschlagen
