application_setup = INSTALACIÓN DE LA APLICACIÓN
guided_setup = Instalación guiada de la aplicación para Windows.
platform_windows = WINDOWS
action_required = ACCIÓN NECESARIA
setup_needs_attention = El instalador requiere tu atención
continue_action = Continuar
ok = Aceptar
cancel = Cancelar
abort = Anular
retry = Reintentar
try_again = Intentar de nuevo
ignore = Ignorar
yes = Sí
no = No
files_in_use = Cierra las aplicaciones que usan archivos instalados y vuelve a intentarlo.
welcome = BIENVENIDO
preparing_setup = Preparando la instalación
checking_installed_version = Comprobando la versión instalada...
version_check = COMPROBACIÓN DE VERSIÓN
newer_version_installed = Hay una versión más reciente instalada
remove_newer_version = Desinstala la versión más reciente antes de instalar esta versión.
close = Cerrar
maintenance = MANTENIMIENTO
manage_installation = Administrar la instalación
already_installed = Live2D Preview ya está instalado. Puedes repararlo o desinstalarlo de este equipo.
uninstall = Desinstalar
repair = Reparar
installation = INSTALACIÓN
ready_to_install = Todo listo para instalar
installation_options = Elige dónde instalar la aplicación y si quieres crear un acceso directo en el escritorio.
installation_folder = Carpeta de instalación
invalid_installation_folder = Introduce una ruta absoluta
browse = Examinar...
create_desktop_shortcut = Crear un acceso directo en el escritorio
install = Instalar
setup = INSTALACIÓN
setup_could_not_continue = La instalación no puede continuar
installed_version_unknown = No se pudo determinar la versión instalada.
installing = INSTALANDO
installing_product = Instalando Live2D Preview
rollback = REVERSIÓN
canceling_and_rolling_back = Cancelando y revirtiendo los cambios
repairing = REPARANDO
repairing_product = Reparando Live2D Preview
removing = DESINSTALANDO
uninstalling_product = Desinstalando Live2D Preview
operation_may_take_a_moment = Esta operación puede tardar unos instantes.
complete = COMPLETADO
application_removed = Aplicación desinstalada
installation_complete = Instalación completada
application_removed_message = La aplicación se ha desinstalado de este equipo.
installation_complete_message = Live2D Preview se ha instalado correctamente.
application_removed_restart_message = La aplicación se ha desinstalado de este equipo. Reinicia Windows para finalizar.
installation_complete_restart_message = Live2D Preview se ha instalado correctamente. Reinicia Windows para finalizar.
canceled = CANCELADO
installation_canceled = Instalación cancelada
no_further_changes = No se realizarán más cambios.
setup_error = ERROR DE INSTALACIÓN
installation_failed = Error de instalación
