application_setup = INSTALLATION DE L’APPLICATION
guided_setup = Installation guidée de votre application Windows.
platform_windows = WINDOWS
action_required = ACTION REQUISE
setup_needs_attention = Le programme d’installation requiert votre attention
continue_action = Continuer
ok = OK
cancel = Annuler
abort = Abandonner
retry = Réessayer
try_again = Réessayer
ignore = Ignorer
yes = Oui
no = Non
files_in_use = Fermez les applications qui utilisent des fichiers installés, puis réessayez.
welcome = BIENVENUE
preparing_setup = Préparation de l’installation
checking_installed_version = Vérification de la version installée...
version_check = VÉRIFICATION DE LA VERSION
newer_version_installed = Une version plus récente est installée
remove_newer_version = Désinstallez la version plus récente avant d’installer cette version.
close = Fermer
maintenance = MAINTENANCE
manage_installation = Gérer l’installation
already_installed = Live2D Preview est déjà installé. Vous pouvez le réparer ou le désinstaller de cet ordinateur.
uninstall = Désinstaller
repair = Réparer
installation = INSTALLATION
ready_to_install = Prêt pour l’installation
installation_options = Choisissez le dossier d’installation et indiquez si un raccourci doit être créé sur le bureau.
installation_folder = Dossier d’installation
invalid_installation_folder = Saisissez un chemin absolu
browse = Parcourir...
create_desktop_shortcut = Créer un raccourci sur le bureau
install = Installer
setup = INSTALLATION
setup_could_not_continue = L’installation ne peut pas continuer
installed_version_unknown = Impossible de déterminer la version installée.
installing = INSTALLATION
installing_product = Installation de Live2D Preview
rollback = ANNULATION DES MODIFICATIONS
canceling_and_rolling_back = Annulation et restauration en cours
repairing = RÉPARATION
repairing_product = Réparation de Live2D Preview
removing = DÉSINSTALLATION
uninstalling_product = Désinstallation de Live2D Preview
operation_may_take_a_moment = Cette opération peut prendre quelques instants.
complete = TERMINÉ
application_removed = Application désinstallée
installation_complete = Installation terminée
application_removed_message = L’application a été désinstallée de cet ordinateur.
installation_complete_message = Live2D Preview a été installé correctement.
application_removed_restart_message = L’application a été désinstallée de cet ordinateur. Redémarrez Windows pour terminer.
installation_complete_restart_message = Live2D Preview a été installé correctement. Redémarrez Windows pour terminer.
canceled = ANNULÉ
installation_canceled = Installation annulée
no_further_changes = Aucune autre modification ne sera effectuée.
setup_error = ERREUR D’INSTALLATION
installation_failed = Échec de l’installation
