application_setup = 애플리케이션 설치
guided_setup = Windows 애플리케이션 설치를 안내합니다.
platform_windows = WINDOWS
action_required = 작업 필요
setup_needs_attention = 설치 프로그램을 확인해 주세요
continue_action = 계속
ok = 확인
cancel = 취소
abort = 중단
retry = 다시 시도
try_again = 다시 시도
ignore = 무시
yes = 예
no = 아니요
files_in_use = 설치된 파일을 사용 중인 애플리케이션을 닫고 다시 시도하세요.
welcome = 시작
preparing_setup = 설치를 준비하는 중
checking_installed_version = 설치된 버전을 확인하는 중...
version_check = 버전 확인
newer_version_installed = 최신 버전이 설치되어 있습니다
remove_newer_version = 이 릴리스를 설치하기 전에 최신 버전을 제거해 주세요.
close = 닫기
maintenance = 유지 관리
manage_installation = 설치 관리
already_installed = Live2D Preview이(가) 이미 설치되어 있습니다. 복구하거나 이 컴퓨터에서 제거할 수 있습니다.
uninstall = 제거
repair = 복구
installation = 설치
ready_to_install = 설치 준비 완료
installation_options = 애플리케이션 설치 위치와 바탕 화면 바로 가기 생성 여부를 선택하세요.
installation_folder = 설치 폴더
invalid_installation_folder = 절대 경로를 입력하세요
browse = 찾아보기...
create_desktop_shortcut = 바탕 화면 바로 가기 만들기
install = 설치
setup = 설치 프로그램
setup_could_not_continue = 설치를 계속할 수 없습니다
installed_version_unknown = 설치된 버전을 확인할 수 없습니다.
installing = 설치 중
installing_product = Live2D Preview 설치 중
rollback = 롤백 중
canceling_and_rolling_back = 취소하고 롤백하는 중
repairing = 복구 중
repairing_product = Live2D Preview 복구 중
removing = 제거 중
uninstalling_product = Live2D Preview 제거 중
operation_may_take_a_moment = 이 작업에는 시간이 걸릴 수 있습니다.
complete = 완료
application_removed = 애플리케이션 제거 완료
installation_complete = 설치 완료
application_removed_message = 이 컴퓨터에서 애플리케이션을 제거했습니다.
installation_complete_message = Live2D Preview을(를) 성공적으로 설치했습니다.
application_removed_restart_message = 이 컴퓨터에서 애플리케이션을 제거했습니다. 완료하려면 Windows를 다시 시작하세요.
installation_complete_restart_message = Live2D Preview을(를) 성공적으로 설치했습니다. 완료하려면 Windows를 다시 시작하세요.
canceled = 취소됨
installation_canceled = 설치 취소됨
no_further_changes = 더 이상 변경하지 않습니다.
setup_error = 설치 오류
installation_failed = 설치 실패
