application_setup = 應用程式安裝程式
guided_setup = 引導你完成 Windows 應用程式安裝。
platform_windows = WINDOWS
action_required = 需要操作
setup_needs_attention = 安裝程式需要你的確認
continue_action = 繼續
ok = 確定
cancel = 取消
abort = 中止
retry = 重試
try_again = 再試一次
ignore = 忽略
yes = 是
no = 否
files_in_use = 關閉正在使用已安裝檔案的應用程式，然後再試一次。
welcome = 歡迎
preparing_setup = 正在準備安裝
checking_installed_version = 正在檢查已安裝的版本...
version_check = 版本檢查
newer_version_installed = 已安裝較新版本
remove_newer_version = 請先解除安裝較新版本，再安裝此版本。
close = 關閉
maintenance = 維護
manage_installation = 管理安裝
already_installed = Live2D Preview 已安裝。你可以修復或從此電腦解除安裝此應用程式。
uninstall = 解除安裝
repair = 修復
installation = 安裝
ready_to_install = 準備安裝
installation_options = 選擇應用程式安裝位置，以及是否建立桌面捷徑。
installation_folder = 安裝資料夾
invalid_installation_folder = 請輸入絕對路徑
browse = 瀏覽...
create_desktop_shortcut = 建立桌面捷徑
install = 安裝
setup = 安裝程式
setup_could_not_continue = 安裝程式無法繼續
installed_version_unknown = 無法判斷已安裝的版本。
installing = 正在安裝
installing_product = 正在安裝 Live2D Preview
rollback = 正在復原
canceling_and_rolling_back = 正在取消並復原
repairing = 正在修復
repairing_product = 正在修復 Live2D Preview
removing = 正在解除安裝
uninstalling_product = 正在解除安裝 Live2D Preview
operation_may_take_a_moment = 此程序可能需要一些時間。
complete = 完成
application_removed = 應用程式已解除安裝
installation_complete = 安裝完成
application_removed_message = 應用程式已從此電腦解除安裝。
installation_complete_message = Live2D Preview 已成功安裝。
application_removed_restart_message = 應用程式已從此電腦解除安裝。請重新啟動 Windows 以完成操作。
installation_complete_restart_message = Live2D Preview 已成功安裝。請重新啟動 Windows 以完成操作。
canceled = 已取消
installation_canceled = 安裝已取消
no_further_changes = 不會再進行其他變更。
setup_error = 安裝錯誤
installation_failed = 安裝失敗
