application_setup = 应用安装程序
guided_setup = 引导你完成 Windows 应用安装。
platform_windows = WINDOWS
action_required = 需要操作
setup_needs_attention = 安装程序需要你的确认
continue_action = 继续
ok = 确定
cancel = 取消
abort = 中止
retry = 重试
try_again = 重试
ignore = 忽略
yes = 是
no = 否
files_in_use = 关闭正在使用已安装文件的应用，然后重试。
welcome = 欢迎
preparing_setup = 正在准备安装
checking_installed_version = 正在检查已安装的版本...
version_check = 版本检查
newer_version_installed = 已安装较新版本
remove_newer_version = 请先卸载较新版本，再安装此版本。
close = 关闭
maintenance = 维护
manage_installation = 管理安装
already_installed = Live2D Preview 已安装。你可以修复或从此电脑卸载该应用。
uninstall = 卸载
repair = 修复
installation = 安装
ready_to_install = 准备安装
installation_options = 选择应用安装位置以及是否创建桌面快捷方式。
installation_folder = 安装文件夹
invalid_installation_folder = 请输入绝对路径
browse = 浏览...
create_desktop_shortcut = 创建桌面快捷方式
install = 安装
setup = 安装程序
setup_could_not_continue = 安装程序无法继续
installed_version_unknown = 无法确定已安装的版本。
installing = 正在安装
installing_product = 正在安装 Live2D Preview
rollback = 正在回滚
canceling_and_rolling_back = 正在取消并回滚
repairing = 正在修复
repairing_product = 正在修复 Live2D Preview
removing = 正在卸载
uninstalling_product = 正在卸载 Live2D Preview
operation_may_take_a_moment = 此过程可能需要一点时间。
complete = 完成
application_removed = 应用已卸载
installation_complete = 安装完成
application_removed_message = 应用已从此电脑卸载。
installation_complete_message = Live2D Preview 已成功安装。
application_removed_restart_message = 应用已从此电脑卸载。请重启 Windows 以完成操作。
installation_complete_restart_message = Live2D Preview 已成功安装。请重启 Windows 以完成操作。
canceled = 已取消
installation_canceled = 安装已取消
no_further_changes = 不会再进行其他更改。
setup_error = 安装错误
installation_failed = 安装失败
