set -eu

if [ -z "${HUXERUI_HOME:-}" ]; then
  echo "error: HUXERUI_HOME is not configured; set it in Config/Local.xcconfig" >&2
  exit 1
fi

HUXERUI_CMAKE_ARCHS=$(printf '%s' "$ARCHS" | tr ' ' ';')
cmake -S "$HUXERUI_PROJECT_ROOT" -B "$HUXERUI_CORE_BUILD_DIR" \
  -DCMAKE_SYSTEM_NAME=iOS \
  -DCMAKE_OSX_SYSROOT="$SDKROOT" \
  -DCMAKE_OSX_ARCHITECTURES="$HUXERUI_CMAKE_ARCHS" \
  -DCMAKE_OSX_DEPLOYMENT_TARGET="$IPHONEOS_DEPLOYMENT_TARGET" \
  -DCMAKE_BUILD_TYPE="$CONFIGURATION" \
  -DHUXERUI_HOME="$HUXERUI_HOME" \
  -DHUXERUI_BUILD_SHARED=OFF \
  -DHUXERUI_BUILD_TESTS=OFF \
  -DHUXERUI_BUILD_EXAMPLES=OFF \
  -DHUXERUI_BUILD_CLI=OFF
cmake --build "$HUXERUI_CORE_BUILD_DIR" --target example_live2d_huxerui_ios_core --parallel "${CMAKE_BUILD_PARALLEL_LEVEL:-8}"
